### ISSUE TITLE
File download link failed

### ISSUE THREAD

**Issue by zhang929821416** [tomasgomes/quantification_nextflow#1]
Thank you for developing this workflow
But you provided AmexG_v6.DD.corrected.round2.chr.fa.gz and AmexG_v6.DD.corrected.round2.masked.unscaffolded.fa download links are failed,Can your provide a valid link?
Thank you vary much

**Comment by tomasgomes** [comment]
hey! I'm not sure which download links you're refering to, since I wasn't aiming at making the FASTA files available myself due to their large size. Originally I think I obtained the transcriptome files from https://www.axolotl-omics.org/assemblies

**Comment by zhang929821416** [comment]
Thank you for your reply
In the script you provided ：instructions_Amex_transcriptome.sh
## get full genome (chromosomes + other contigs)
wget https://www.dropbox.com/sh/64jj2pg2wj1s3cp/AAB12E_ZhANIEVKQmVpm8UKNa/AmexG_v6.DD.corrected.round2.chr.fa.gz
wget https://www.dropbox.com/sh/64jj2pg2wj1s3cp/AAB4WJi74cVrdw9TmrjQpG39a/AmexG_v6.DD.corrected.round2.masked.unscaffolded.fa
They look like processed files, so can you provide a download link for them
Thank you very much

**Comment by tomasgomes** [comment]
ah! yes, i have those paths in that file since originally that's how our collaborators shared them with me. so that was meant as a personal annotation rather than a permanent repository, since those files were not hosted by me, and I have no plans to making them available myself. but as i said in my previous comment, these files should be the same as those hosted by the Axolotl-omics database, so that's where I would look for them

**Comment by zhang929821416** [comment]
Thank you for your reply. I will download the database file
